### ISSUE TITLE
AttributeError: 'int' object has no attribute 'out_vector_size'

### ISSUE THREAD

**Issue by VogtAI** [bgavran/DNC#1]
Downloaded as is and got the following error:

`Traceback (most recent call last):
  File "main.py", line 44, in <module>
    dnc = DNC(Hp.batch_size, controller, task.vector_size, Hp.Mem, initializer=weight_initializer, initial_stddev=0.1)
  File "/home/maik/kaggle/src/controller_implementations/dnc/dnc.py", line 20, in __init__
    self.controller_output_size = self.controller.out_vector_size
AttributeError: 'int' object has no attribute 'out_vector_size'
`

**Comment by bgavran** [comment]
I seem to have introduced a bug in the last commit, but that's fixed now.
Now it should work out of the box.
I also added some basic usage instructions.
