### ISSUE TITLE
unsupported operand type(s) for @: 'Tensor' and 'Variable'

### ISSUE THREAD

**Issue by PaulDaoudi** [bgavran/DNC#8]
Hello, I want to compare the lstm and the dnc results as you did. However, when I run your code main.py in the memory part, I have the following problem : 

File "/Users/pauldaoudi1/Downloads/DNC-master-2/src/controller_implementations/dnc/memory.py", line 92, in step
    interface_vector = controller_output @ self.interface_weights  # shape [batch_size, interf_vector_size]

TypeError: unsupported operand type(s) for @: 'Tensor' and 'Variable'.

Do you have an idea where the error could be ? 
Thank you very much.

Paul.

**Comment by bgavran** [comment]
That looks a bit strange, what version of TensorFlow are you using?

**Comment by PaulDaoudi** [comment]
My mistake, I have changed my TensorFlow version to 1.7 and it works perfectly, thank you very much.

I have another question though.  I would like to see for myself how the LSTM works and I saw that it was already implemented. Do you know how can I run it on the examples ?

**Comment by bgavran** [comment]
There are instructions on how to run just the LSTM at the top of the readme of this repository.
Ask if you get stuck on a particular issue.

**Comment by PaulDaoudi** [comment]
Yes sorry, I was focused on your chapter which describes the comparaison part between LSTM and DNC.

Thank you very much, your work is really impressive!
